#-
#  outputFilename: georgia_data.csv
#  sheetId: 1rumw5gXUbTGLU4fMrftfIYiMrtBeH2FGnXludd6SwZ8
#  range: "A1:E"
-
  outputFilename: georgia_ev_automotive.csv
  sheetId: 1OX8TsLby-Ddn8WHa7yLKNpEERYN_RlScMrC0sbnT1Zs
  range: "Automotive!A1:E"
-
  outputFilename: georgia_ev_repair.csv
  sheetId: 1OX8TsLby-Ddn8WHa7yLKNpEERYN_RlScMrC0sbnT1Zs
  range: "Repair!A1:E"
